
[drives.root]
builder = "docker"
dockerfile = ".rootfs/Dockerfile"
extra-size = "16Mb"
format = "ext2"

# cartesapp command to generate rootfs
# cartesapp build --drives-only --config-file .rootfs/config.toml
