
[drives.root]
builder = "docker"
dockerfile = ".rootfs/Dockerfile"
extra_size = "16Mb"
format = "ext2"

# cartesapp command to generate rootfs
# cartesapp build --drives-only --drive-config root.target=dist --config-file .rootfs/config.toml
